server:
  port: 8020
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
        secret-key: SecretKey012345678901234567890123456789012345678901234567890123456789

##nacos访问策略调整 方式二 (两种方式 二选一就行)
#stock-service:
#  ribbon:
#    NFLoadBalancerRuleClasslane: com.alibaba.cloud.nacos.ribbon.NacosRule
