server:
  port: 8060
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/seata_store?useSSL=false&serverTimezone=UTC
    dricer-class-name: com.mysql.jdbc.Driver
  application:
    name: seata-store
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
seata:
  tx-service-group: my_test_tx_group
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      application: seata-server
      group: DEFAULT_GROUP
  config:
    type: nacos
    nacos:
      access-key: localhost:8848
      username: nacos
      password: nacos
      group: DEFAULT_GROUP