server:
  port: 8050

spring:
  application:
    name: seata-order
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/seata_order?useSSL=false&serverTimezone=UTC
    dricer-class-name: com.mysql.jdbc.Driver



feign:
  client:
    config:
      default:
        loggerLevel: FULL

seata-store:
  ribbon:
    NFLoadBancerRuleClassName: com.netflix.loadbalancer.RandomRule


seata:
  tx-service-group: my_test_tx_group
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      application: seata-server
      group: DEFAULT_GROUP
  config:
    type: nacos
    nacos:
      access-key: localhost:8848
      username: nacos
      password: nacos
      group: DEFAULT_GROUP